server:
  port: 8081
  servlet:
    context-path: '/candidato/'

spring:
  application:
    name: bercalini-candidato-service
  datasource:
    url: jdbc:postgresql://localhost:5432/candidato
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true

logging:
  level:
    com.ead: TRACE
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: INFO


eureka:
  client:
    service-url:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost

bercalini:
  api:
    url:
      vaga: 'http://bercalini-vaga-service/vaga'
